import { useState } from 'react';
import { ArrowUpRight, Folder, FolderOpen, Pin, Plus, Trash2 } from 'lucide-react';
import { native } from '../services/native';
import { age } from '../services/refresh';
import { Modal } from './Modal';
import type { Project } from '../types';
import type { HubView } from '../stores/useHub';
export function Projects({hub,compact=false}:{hub:HubView;compact?:boolean}){
 const [edit,setEdit]=useState<Project>();const [selected,setSelected]=useState<Record<string,string>>({});
 const projects=[...hub.store.projects].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||(b.lastOpenedAt??'').localeCompare(a.lastOpenedAt??''));
 const add=()=>setEdit({id:'',name:'',path:'',preferredProfileId:null,pinned:false,lastOpenedAt:null});
 return <section className="projects-section"><div className="section-heading"><div><h2>{compact?'Pick up where you left off':'Your projects'}</h2><span>{compact?'A familiar workspace. The identity you choose.':'Keep each workspace close, with a profile preference of its own.'}</span></div><button className="text-button" onClick={add}><Plus size={14}/> Add project</button></div>
  {!projects.length?<button className="project-empty" onClick={add}><FolderOpen size={26}/><span><strong>Your next session starts here</strong><small>Add a project folder and choose a preferred profile.</small></span><Plus size={18}/></button>:<div className="project-list">{(compact?projects.slice(0,4):projects).map(p=>{const profileId=selected[p.id]??p.preferredProfileId??'';return <div className="project-row" key={p.id}><div className="folder-symbol"><Folder size={19}/></div><button className="project-name" onClick={()=>setEdit(p)}><strong>{p.name}{p.pinned&&<Pin size={11}/>}</strong><span title={p.path}>{p.path}</span></button><span className="project-time">{age(p.lastOpenedAt,hub.now)}</span><select aria-label={`Profile for ${p.name}`} value={profileId} onChange={e=>setSelected(s=>({...s,[p.id]:e.target.value}))}><option value="">Choose profile</option>{hub.store.profiles.map(p=><option key={p.id} value={p.id}>{p.name}{p.availability!=='available'?' · reserved':''}</option>)}</select><button className="secondary" disabled={!profileId||!!hub.busy[profileId]} onClick={()=>void hub.launch(profileId,p.id)}>Open <ArrowUpRight size={15}/></button></div>;})}</div>}
  {edit&&<ProjectEditor project={edit} hub={hub} onClose={()=>setEdit(undefined)}/>}
 </section>;
}
function ProjectEditor({project,hub,onClose}:{project:Project;hub:HubView;onClose:()=>void}){
 const [p,setP]=useState(project);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 return <Modal title={p.id?'Project settings':'Add a project'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setSaving(true);try{await native('save_project',{project:p});await hub.reload();onClose();}catch(e){setError(String(e));}finally{setSaving(false);}}}><label>Project name<input autoFocus required value={p.name} maxLength={80} placeholder="Freebuff" onChange={e=>setP({...p,name:e.target.value})}/></label><label>Project folder<div className="path-input"><input required value={p.path} placeholder="C:\Dev\freebuff" onChange={e=>setP({...p,path:e.target.value})}/><button type="button" className="secondary" aria-label="Choose project folder" onClick={async()=>{try{const path=await native<string|null>('choose_path',{kind:'folder'});if(path)setP({...p,path});}catch(e){setError(String(e));}}}><FolderOpen size={16}/></button></div></label><label>Preferred profile<select value={p.preferredProfileId??''} onChange={e=>setP({...p,preferredProfileId:e.target.value||null})}><option value="">Choose at launch</option>{hub.store.profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="check"><input type="checkbox" checked={p.pinned} onChange={e=>setP({...p,pinned:e.target.checked})}/>Pin to the top</label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-footer">{p.id?<button type="button" className="text-button danger" onClick={async()=>{try{await native('remove_project',{id:p.id});await hub.reload();onClose();}catch(e){setError(String(e));}}}><Trash2 size={14}/>Remove shortcut</button>:<span>Folder contents stay in place.</span>}<button disabled={saving} className="primary">Save project</button></div></form></Modal>;
}
