import { AppUpdates } from './AppUpdates';
import { usePrivacy } from './StreamerMode';
import { useState } from 'react';
import { Check, Download, FolderOpen, RefreshCw, Stethoscope, Upload } from 'lucide-react';
import type { HubView } from '../stores/useHub';
import { native } from '../services/native';
import { defaultSettings, type Installation, type Settings as SettingsModel } from '../types';
export function Settings({hub}:{hub:HubView}){
 const privacy=usePrivacy();
 const [s,setS]=useState(hub.store.settings);const [message,setMessage]=useState('');const [error,setError]=useState('');const [report,setReport]=useState('');const [saving,setSaving]=useState(false);
 const patch=(value:Partial<SettingsModel>)=>setS(s=>({...s,...value}));
 async function save(){setSaving(true);setError('');try{await native('save_settings',{settings:s});await hub.reload();hub.setInstallation(await native<Installation>('detect_codex'));setMessage('Preferences saved');}catch(e){setError(String(e));}finally{setSaving(false);}}
 async function choose(key:'desktopExe'|'cliExe'|'profileRoot'){try{const p=await native<string|null>('choose_path',{kind:key==='profileRoot'?'folder':'exe'});if(p)patch({[key]:p});}catch(e){setError(String(e));}}
 const toggle=(key:'autoRefresh'|'refreshOnFocus'|'showStale'|'reducedMotion'|'minimizeToTray'|'startup'|'hideAfterLaunch',title:string,description:string)=><label className="setting-toggle"><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" role="switch" checked={s[key]} onChange={e=>patch({[key]:e.target.checked})}/></label>;
 return <div className="settings-page"><div className="page-heading"><div className="eyebrow">Preferences</div><h1>Settings</h1><p>Manage usage refresh, app behaviour, and local storage.</p></div><div className="settings-layout"><div className="settings-main">
 <section className="settings-panel"><h2>Your existing Codex workspace</h2><p className="muted">All accounts open the same Codex Desktop workspace. The Hub requests a normal quit and restart to load your saved login. Use Quit rather than Sign out, which can revoke saved credentials. Your sidebar, tasks, projects, and settings stay in place.</p><p className="path-note">{privacy.active?'Workspace folder hidden':hub.workspace?.home??hub.installation?.existingHome}</p><h2>Codex installation</h2>{privacy.active&&<p className="privacy-note">Paths and diagnostics are hidden. Turn streamer mode off to edit paths or use file dialogs.</p>}<p className="muted">Detected automatically. Set an override only when needed.</p>{(['desktopExe','cliExe','profileRoot'] as const).map(key=><label key={key}>{key==='desktopExe'?'Codex Desktop':key==='cliExe'?'Codex CLI':'New profile storage'}<div className="path-input"><input disabled={privacy.active} value={privacy.active?'Path hidden':s[key]??''} placeholder={privacy.active?'Path hidden':key==='desktopExe'?hub.installation?.desktop??'Not detected':key==='cliExe'?hub.installation?.cli??'Not detected':'Default · your user folder'} onChange={e=>patch({[key]:e.target.value||null})}/><button className="secondary" disabled={privacy.active} aria-label={`Choose ${key}`} onClick={()=>void choose(key)}><FolderOpen size={15}/></button></div></label>)}<p className="muted small">Changing storage affects new profiles. Existing profiles keep their location.</p></section>
 <section className="settings-panel"><h2>Live usage</h2>{toggle('autoRefresh','Keep allowances current','Refresh periodically while the dashboard is visible.')}<label className="interval-setting"><span>Refresh interval</span><select value={s.refreshSeconds} onChange={e=>patch({refreshSeconds:Number(e.target.value)})}>{[30,60,120,300,600,1800,3600].map(n=><option key={n} value={n}>{n<60?`${n} seconds`:`${n/60} ${n===60?'minute':'minutes'}`}</option>)}</select></label>{toggle('refreshOnFocus','Refresh when you return','Check again after at least 15 seconds away.')}{toggle('showStale','Keep last confirmed values visible','Cached values always carry their original timestamp.')}<button className="text-button" onClick={()=>void hub.refreshAll()}><RefreshCw size={14}/> Refresh all now</button></section>
 <section className="settings-panel"><h2>Appearance & behaviour</h2><label className="interval-setting"><span>Density</span><select value={s.density} onChange={e=>patch({density:e.target.value})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label>{toggle('reducedMotion','Reduce motion','Keep transitions minimal.')}{toggle('minimizeToTray','Close to system tray','Keep your profile launcher within reach.')}{toggle('startup','Launch at Windows startup','Start the Hub quietly in the system tray.')}{toggle('hideAfterLaunch','Hide Hub after opening Codex','Minimize the Hub after a successful launch.')}</section>
 </div><aside className="settings-aside"><section className="settings-panel"><span className="feature-icon"><Stethoscope size={22}/></span><h2>Diagnostics</h2><p className="muted">Check installation and profile authentication without exposing credentials.</p><select aria-label="Profile to diagnose" id="diagnostic-profile"><option value="">Installation only</option>{hub.store.profiles.map(p=><option key={p.id} value={p.id}>{privacy.profileName(p)}</option>)}</select><button className="secondary full" onClick={async()=>{setReport('Checking…');try{const id=(document.getElementById('diagnostic-profile') as HTMLSelectElement).value;const result=await native('diagnostics',{id:id||null});setReport(JSON.stringify(result,null,2));}catch(e){setReport(String(e));}}}>Run diagnostics</button>{report&&<pre className="diagnostic-output">{privacy.detail(report)}</pre>}</section><AppUpdates/><section className="settings-panel"><h2>Import & export</h2><p className="muted">Safe exports contain profile labels and project shortcuts. Authentication stays with Codex.</p><button disabled={privacy.active} className="secondary full" onClick={async()=>{try{if(await native('export_config'))setMessage('Safe configuration exported');}catch(e){setError(String(e));}}}><Download size={14}/> Export configuration</button><button disabled={privacy.active} className="secondary full" onClick={async()=>{try{if(await native('import_config')){await hub.reload();setMessage('Profiles imported. Connect each account to finish setup.');}}catch(e){setError(String(e));}}}><Upload size={14}/> Import configuration</button><p className="muted small">Import adds fresh profiles and project shortcuts. Existing profiles and preferences stay in place.</p><button className="text-button" onClick={()=>{setS({...defaultSettings});setMessage('Default preferences loaded. Save to apply.');}}>Reset preferences</button></section></aside></div>
 <div className="settings-save">{error?<span className="form-error" role="alert">{privacy.detail(error)}</span>:<span className="muted">{message||'Changes apply when you save.'}</span>}<button className="primary" disabled={saving} onClick={()=>void save()}><Check size={15}/>{saving?'Saving…':'Save preferences'}</button></div></div>;
}
