import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, Command, FolderOpen, Grid2X2, Layers, Plus, RefreshCw, Settings2, ShieldCheck, X, Zap } from 'lucide-react';
import { useHub } from './stores/useHub';
import { WorkspaceNotice } from './components/WorkspaceNotice';
import { TitleBar } from './components/TitleBar';
import { WorkspaceArtwork } from './components/WorkspaceArtwork';
import { ProfileCard } from './components/ProfileCard';
import { ProfileEditor } from './components/ProfileEditor';
import { Projects } from './components/Projects';
import { Settings } from './components/Settings';
import { CommandPalette, type Command as PaletteCommand } from './components/CommandPalette';
import { mockMode, native, nativeAvailable, onNative } from './services/native';
import { effectiveState } from './services/refresh';
import type { Profile } from './types';
export default function App(){
 const [accountFilter,setAccountFilter]=useState('all');
 const hub=useHub();const [page,setPage]=useState('dashboard');const [palette,setPalette]=useState(false);const [editor,setEditor]=useState<{profile?:Profile;existingHome?:string}>();
 const {store}=hub;const live=store.profiles.filter(p=>effectiveState(store.usageCache[p.id],hub.now,store.settings.refreshSeconds)==='live').length;const syncing=store.profiles.filter(p=>store.usageCache[p.id]?.state==='refreshing').length;const available=store.profiles.filter(p=>p.availability==='available').length;
 const profiles=[...store.profiles].sort((a,b)=>Number(a.availability!=='available')-Number(b.availability!=='available')||a.createdAt.localeCompare(b.createdAt));
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(p=>!p);}};window.addEventListener('keydown',key);let cleanup:(()=>void)|undefined;void onNative<string>('navigate',setPage).then(off=>cleanup=off);return()=>{window.removeEventListener('keydown',key);cleanup?.();};},[]);
 const commands:PaletteCommand[]=[{id:'overview',label:'Open overview',detail:'All accounts and allowances',run:()=>setPage('dashboard')},{id:'projects',label:'Open projects',detail:'Your saved project shortcuts',run:()=>setPage('projects')},{id:'refresh-all',label:'Refresh all usage',detail:'Get current allowances for every profile',run:()=>void hub.refreshAll()},{id:'add',label:'Add account',detail:'Save another account for your existing workspace',run:()=>setEditor({})},{id:'settings',label:'Open settings',detail:'Preferences and diagnostics',run:()=>setPage('settings')}];
 async function prepareFour(){try{const presets=[{name:'Pro',plan:'pro',accent:'violet'},{name:'Plus 1',plan:'plus',accent:'blue'},{name:'Plus 2',plan:'plus',accent:'mint'},{name:'Plus 3',plan:'plus',accent:'amber'}];for(const preset of presets){if(hub.store.profiles.some(p=>p.name===preset.name))continue;await native('save_profile',{input:{...preset,id:null,availability:'available',existingHome:null}});}await hub.reload();void hub.refreshAll();}catch(e){hub.setError(String(e));}}
 for(const p of profiles){commands.push({id:`launch-${p.id}`,label:`Open Codex — ${p.name}`,detail:p.availability.replace('-',' '),run:()=>void hub.launch(p.id)},{id:`refresh-${p.id}`,label:`Refresh usage — ${p.name}`,detail:'Request live limits from Codex',run:()=>void hub.refresh(p.id)});for(const project of store.projects)commands.push({id:`project-${project.id}-${p.id}`,label:`Open ${project.name} with ${p.name}`,detail:project.preferredProfileId===p.id?'Preferred for this project':p.availability.replace('-',' '),run:()=>void hub.launch(p.id,project.id)});}
 const visibleProfiles=profiles.filter(p=>accountFilter==='all'||(accountFilter==='available'?p.availability==='available':p.availability!=='available'));
 return <div className={`app-shell ${store.settings.reducedMotion?'reduced-motion':''} density-${store.settings.density}`}>
 <TitleBar onSearch={()=>setPalette(true)} onError={hub.setError} closeToTray={store.settings.minimizeToTray}/><aside className="sidebar"><div className="space-identity"><span><Layers size={18}/></span><div><strong>Personal workspace</strong><small>On this device</small></div></div><div className="workspace-label">WORKSPACE</div><nav>{[{id:'dashboard',label:'Overview',icon:Grid2X2},{id:'accounts',label:'Profiles',icon:Layers},{id:'projects',label:'Projects',icon:FolderOpen}].map(({id,label,icon:Icon})=><button key={id} className={page===id?'selected':''} onClick={()=>setPage(id)}><Icon size={17}/>{label}{id==='accounts'&&<span>{store.profiles.length}</span>}</button>)}</nav><button className="sidebar-command" onClick={()=>setPalette(true)}><Command size={15}/> Quick launcher <kbd>Ctrl K</kbd></button><div className="sidebar-bottom"><div className="local-note"><ShieldCheck size={17}/><div>Local by design<span>Your profiles. Your machine.</span></div></div><button className={`settings-nav ${page==='settings'?'selected':''}`} onClick={()=>setPage('settings')}><Settings2 size={17}/> Settings<span>↗</span></button><div className="version">DRAEY <span>v0.1.0-alpha.2 · Windows</span></div></div></aside>
 <main>
 {mockMode&&<div className="mode-banner">DEVELOPMENT DEMO · Simulated limits and launches · No connected accounts</div>}
 {!nativeAvailable&&!mockMode&&<div className="mode-banner">Browser preview · Open the desktop build to connect accounts and retrieve real usage</div>}
 <div className="main-content"><WorkspaceNotice workspace={hub.workspace} profiles={store.profiles} onCancel={()=>void hub.cancelSwitch()}/>{page==='settings'?<Settings hub={hub}/>:page==='projects'?<><div className="page-heading"><div className="eyebrow">YOUR NEXT CHAPTER</div><h1>Back to building.</h1><p>Familiar projects. A deliberate choice of identity.</p></div><Projects hub={hub}/></>:<>
 <div className="dashboard-heading"><WorkspaceArtwork/><div className="page-heading"><div className="eyebrow"><span/> {page==='accounts'?'ACCOUNTS & ALLOWANCES':'A LITTLE SPACE TO DO GREAT WORK'}</div><h1>{page==='accounts'?'Your accounts.':'Welcome to your workspace.'}</h1><p>Your accounts at a glance. Your next session, one click away.</p></div><button className="primary add-account" onClick={()=>setEditor({})}><Plus size={16}/> Add account</button></div>
 {!store.profiles.length&&hub.loaded?<section className="onboarding"><div className="onboarding-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit-core"><Layers size={34}/></div><span className="orbit-node node-one"/><span className="orbit-node node-two"/><span className="orbit-node node-three"/></div><div className="onboarding-copy"><span className="eyebrow">A LITTLE SETUP. A LOT MORE FOCUS.</span><h2>Every profile.<br/>One command centre.</h2><p>Connect your accounts once. See their current allowances and open the Codex workspace you choose.</p><button className="primary" onClick={()=>setEditor({})}>Connect your first account <ArrowRight size={16}/></button>{hub.installation?.existingHome&&<button className="text-button" onClick={()=>setEditor({existingHome:hub.installation!.existingHome!})}>Add existing Codex profile <ArrowUpRight size={14}/></button>}<div className="detection-note"><span className={hub.installation?.desktop?'connection-dot':'neutral-dot'}/>{hub.installation?.desktop?'Codex Desktop detected':hub.installation?'Locate Codex Desktop in Settings':'Checking your Codex installation…'}</div></div></section>:<>
 <div className="summary-strip"><div><strong>{store.profiles.length.toString().padStart(2,'0')}</strong><span>profiles</span></div><div><strong>{available.toString().padStart(2,'0')}</strong><span>ready to choose</span></div><div className="sync-summary"><span className={syncing?'sync-glyph spin':'sync-glyph'}><RefreshCw size={17}/></span><span><strong>{syncing?`Syncing ${syncing} ${syncing===1?'profile':'profiles'}…`:live===store.profiles.length&&live?'All accounts up to date':`${live}/${store.profiles.length} accounts live`}</strong><small>{syncing?'Cards update as responses arrive':live===store.profiles.length&&live?'Current allowances, confirmed by Codex':'Each profile reports its own connection state'}</small></span></div><button className="secondary" onClick={()=>void hub.refreshAll()} disabled={syncing===store.profiles.length&&syncing>0}><RefreshCw size={14} className={syncing?'spin':''}/> Refresh all</button></div>
 <section className="accounts-section"><div className="account-toolbar"><div className="account-tabs" aria-label="Filter accounts">{[{id:'all',label:'All accounts',count:profiles.length},{id:'available',label:'Available',count:available},{id:'reserved',label:'Reserved',count:profiles.length-available}].map(tab=><button key={tab.id} aria-pressed={accountFilter===tab.id} className={accountFilter===tab.id?'active':''} onClick={()=>setAccountFilter(tab.id)}>{tab.label}<span>{tab.count}</span></button>)}</div><span className="small muted"><i className="connection-dot"/> {store.settings.autoRefresh?`Auto-refresh ${store.settings.refreshSeconds}s`:'Auto-refresh off'}</span></div><div className="profile-grid">{visibleProfiles.map(p=><ProfileCard key={p.id} profile={p} snapshot={store.usageCache[p.id]} settings={store.settings} now={hub.now} active={hub.workspace?.activeProfileId===p.id} busy={hub.busy[p.id]} onLaunch={()=>void hub.launch(p.id)} onRefresh={()=>void hub.refresh(p.id)} onEdit={()=>setEditor({profile:p})} onLogin={()=>void hub.login(p.id)}/>)}{!hub.loaded&&[1,2,3].map(n=><div className="profile-card loading-card" key={n}><i/><i/><i/></div>)}</div>{hub.loaded&&!visibleProfiles.length&&<div className="filter-empty">No {accountFilter} accounts. <button className="text-button" onClick={()=>setAccountFilter('all')}>Show all accounts</button></div>}</section></>}
 {!store.profiles.length&&nativeAvailable&&<div className="setup-banner"><div><strong>Bringing more than one account?</strong><p>Create Pro, Plus 1, Plus 2, and Plus 3 together. Connect each when you’re ready.</p></div><button className="secondary" onClick={()=>void prepareFour()}>Prepare four profiles <Plus size={14}/></button></div>}
 {page==='dashboard'&&<Projects hub={hub} compact/>}<div className="footnote"><ShieldCheck size={13}/><span>Authentication stays with Codex. You stay in control.</span><span><Zap size={12}/> Built for uninterrupted work</span></div>
 </>}</div></main>
 {hub.error&&<div className="toast error-toast" role="alert"><div><strong>Something needs your attention</strong><p>{hub.error}</p></div><button className="icon-button" aria-label="Dismiss error" onClick={()=>hub.setError('')}><X size={16}/></button></div>}
 {Object.entries(hub.busy).filter(([,s])=>s.includes('sign-in')).map(([id,s])=><div className="login-toast" key={id}><RefreshCw size={15} className="spin"/><span>{store.profiles.find(p=>p.id===id)?.name} · {s}</span><button className="text-button" onClick={()=>void native('cancel_login',{id})}>Cancel</button></div>)}
 {editor&&<ProfileEditor profile={editor.profile} existingHome={editor.existingHome} hub={hub} onClose={()=>setEditor(undefined)}/>}{palette&&<CommandPalette commands={commands} onClose={()=>setPalette(false)}/>}
 </div>;
}

